services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php
    volumes:
      - ${PROJECT_PATH}:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    networks:
      - db_network

networks:
  db_network:
    external: true