FROM php:8.1-cli

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       git \
       zip \
       unzip \
       libzip-dev \
       libpng-dev \
       libjpeg-dev \
       libfreetype6-dev \
       libonig-dev \
       libxml2-dev \
       libssl-dev \
       pkg-config \
       curl \
       libicu-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) pdo pdo_mysql mbstring exif pcntl bcmath gd zip intl opcache \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html

RUN usermod -u 1000 www-data || true

EXPOSE 8000

# 保持容器运行
CMD ["tail", "-f", "/dev/null"]
#CMD ["php", "-S", "0.0.0.0:8000", "-t", "/var/www/html"]
